version: '3.8'

services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data even after container is removed

volumes:
  postgres_data:
