spring:
  application:
    name: perfsave
  jpa:
    hibernate:
      ddl-auto: none
    # show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresdb
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-location: classpath:sql/schema.sql
logging:
  level:
    com.thinkitdevit.perfsave: INFO
